spring.application.name=graphql
server.port=8080
# spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.websocket.path=/graphql-ws # pour les Subscriptions

# postgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/graphql_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true